default:
 data.availability.threshold : 0.8
 data.availability.threshold.averaging : 0.3
 database.na.value : -9999
 qc.threshold : [0, 1]
 obj.main.class : "mqm.data.container"
 obj.timeseries.class : "mqm.data.timeseries"
 obj.timeseries.meta.class : "mqm.meta.timeseries"

test:
 test.data.dir : "/home/dirksen/Hackathon-RDWD-QualityMonitoring/data/testdata/"
 database.max.records : -1

production:
 inherits: test
 database.max.records : -1
