test:
  test.data.dir : "/home/dirksen/Hackathon-RDWD-QualityMonitoring/data/testdata/"
  dbname : "mqm_db"
  username : "MQMuser"
  password : "NA"
  host : "145.23.219.9"
  port : 3306
  min.NA : 0.8
  
production:
  inherits: test
  dataset: "data.csv"