default:
  dbname : "mqm_db"
  username : "MQMuser"
  password : "NA"
  host : "145.23.219.9"
  port : 3306
  data.availability.threshold : 0.8

test:
  test.data.dir : "/home/dirksen/Hackathon-RDWD-QualityMonitoring/data/testdata/"
  
production:
  inherits: test
